'use client';
import { PageLoading } from '@/app/_common/components/PageLoading';
import { AuthContextProvider } from '@/app/_common/contexts/AuthContext';
import { persistor, store } from '@/app/_common/redux/store';
import { theme } from '@/app/_common/theme/theme';
import { Box } from '@mui/material';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import { LocalizationProvider } from '@mui/x-date-pickers';
import { AdapterDateFns } from '@mui/x-date-pickers/AdapterDateFnsV3';
import { Provider as ReduxProvider } from 'react-redux';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { PersistGate } from 'redux-persist/lib/integration/react';
import './globals.css';

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <LocalizationProvider dateAdapter={AdapterDateFns}>
              <ReduxProvider store={store}>
                <PersistGate loading={<PageLoading />} persistor={persistor}>
                  <AuthContextProvider>
                    <Box
                      sx={{
                        display: 'flex',
                        flexDirection: 'column',
                        minHeight: '100vh',
                        backgroundColor: (theme) =>
                          theme.palette.background.default,
                      }}
                    >
                      {children}
                    </Box>
                  </AuthContextProvider>
                </PersistGate>
              </ReduxProvider>

              <ToastContainer />
            </LocalizationProvider>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
